# Generated by Django 5.1 on 2024-08-14 15:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/', verbose_name='Profile Image')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('residence', models.CharField(max_length=100, verbose_name='Residence')),
                ('address', models.CharField(max_length=100, verbose_name='Address ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number with country code')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('linkedin', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('cv_file', models.FileField(upload_to='cvs/')),
            ],
            options={
                'verbose_name': 'Me',
                'verbose_name_plural': 'Me',
            },
        ),
    ]
