# Generated by Django 5.1 on 2024-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_me_facebook_alter_me_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWithMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact With Me',
                'verbose_name_plural': 'Contact With Me',
            },
        ),
    ]
