# Generated by Django 5.1 on 2024-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatIDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255, verbose_name='Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Topic')),
                ('text', models.TextField(verbose_name='About Experiance')),
            ],
            options={
                'verbose_name': 'What I Do',
                'verbose_name_plural': 'What I Do',
            },
        ),
    ]
