# Generated by Django 5.1 on 2024-08-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_whatido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('url', models.URLField(verbose_name='Client Website or Project URL')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.CreateModel(
            name='FunFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.PositiveIntegerField(verbose_name='Happy Clients')),
                ('working_hours', models.PositiveIntegerField(verbose_name='Working Hours')),
                ('awards_won', models.PositiveIntegerField(verbose_name='Awards Won')),
            ],
            options={
                'verbose_name': 'Fun Facts',
                'verbose_name_plural': 'Fun Facts',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/', verbose_name='Image')),
                ('text', models.TextField(verbose_name='About Worker')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
            ],
            options={
                'verbose_name': 'Testimonials',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
