# Generated by Django 5.1 on 2024-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_certificates_education_knowledges_portfoliocategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Image')),
                ('image_full', models.ImageField(upload_to='Blog/full/', verbose_name='Image Full')),
                ('main_tag', models.CharField(max_length=15, verbose_name='Main Tag')),
                ('title', models.CharField(default='default_title_class', max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Creation Day')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('linkedin', models.URLField(verbose_name='Linkedin')),
                ('tags', models.ManyToManyField(to='main.tag')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
